# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#
# Author: Colin O'Dowd

from PyQt5 import QtCore, QtGui, QtWidgets 
from types import FrameType
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from UISetup import Ui_MainWindow
import time
import sys

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow().setupUi(MainWindow)
    time.sleep(0.1) #delay for checking if camera is connected
    MainWindow.show()
    sys.exit(app.exec_())
